load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-tools/devtools-messenger",
    dependencies = [
      "@npm//tiny-uid",
      "@npm//@types/node",
    ],
    peer_dependencies = [
      "@npm//typescript"
    ],
)
