load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-tools/devtools-types",
    dependencies = [
        "@npm//@player-ui/types",
        "//devtools/messenger:@player-tools/devtools-messenger",
    ],
)