load("//:index.bzl", "javascript_pipeline")

javascript_pipeline(
    name = "@player-tools/devtools-flipper-desktop-client",
    dependencies = [
      "@npm//flipper-plugin",
      "@npm//react",
      "@npm//react-dom",
      "//devtools/client:@player-tools/devtools-client",
    ],
)
